# Generated by Django 5.0.2 on 2024-02-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybud', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
